// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function add(a, b) {
  return a + b | 0;
}

Pervasives.print_int(11);

export {
  add ,
  
}
/*  Not a pure module */
